apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  ports:
  - port: 3000
  selector:
    app: course-front
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-front
spec:
  selector:
    matchLabels:
      app: course-front
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: course-front
    spec:
      containers:
      - name: front-js
        image: danielesiddi/course-front
        ports:
        - containerPort: 3000
        env:
          # Use secret in real usage
        - name: BACKEND_HOSTNAME
          value: back:6000

